#!/bin/bash

docker-compose -f frontend/docker-compose.yml up -d
docker-compose -f backend/docker-compose.yml up -d

echo 'Loading Pokedex...'
sleep 4
echo 'FrontEnd running on http://localhost'
echo 'BackEnd running on http://localhost:8081'