version: '2'

services:
    php:
      container_name: pokedex_php
      build: ./docker/php-fpm
      volumes:
        - ./:/var/www
      env_file:
        - ./docker/env
      links:
        - mariadb

    nginx:
      container_name: pokedex_nginx
      build: ./docker/nginx
      env_file:
        - ./docker/env
      ports:
        - "80:80"
      env_file:
        - ./docker/env
      volumes_from:
        - php

    mariadb:
      container_name: pokedex_mariadb
      image: mariadb:latest
      volumes:
        - ./docker/mariadb/data:/var/lib/mysql
      env_file:
        - ./docker/env
      ports:
        - "3306:3306"