#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

echo '#####################################'
echo 'Loading pokedex...'
echo 'Running composer...'
echo '#####################################'
composer install --prefer-dist --no-interaction

echo '#####################################'
echo 'BackEnd ready http://localhost:8081/api/pokemons'
echo 'FrontEnd if you run start script on http://localhost/'
echo '#####################################'

exec "$@"
